---
title: "work_flow"
author: "Adam A. Bramlett"
date: "2023-11-03"
output: html_document
---
```{r}
library(dplyr)
library(utils)
library(tidyr)
library(readr)
library(purrr)
library(openxlsx)
library(stringr)


```

```{r}
master_path<-"/Users/adambramlett/scripts/music_project_23/data"
project<-"data_exp_141883-v12"
version <- sub("data_exp_", "", project)
file_path<-file.path(master_path,project)
```

```{r}
#read in all behavioral data
pattern= "data_exp"
list.files(path = file_path,pattern = pattern,full.names = TRUE)
data <- list.files(file_path, pattern, full.names = TRUE) %>% 
  map_df(~read_csv(.x) %>% mutate(across(.fns = as.character))) %>%
  type_convert()
```
```{r}
list.files(file.path(master_path,"workflow_data"))
node_data<-read.csv(file.path(master_path,"workflow_data","141883-v12_node_exp_spreadhseet_key.csv"))
counts<-node_data%>%group_by(Task_Name)%>%count()
node_data<-node_data%>%left_join(counts)%>%
  filter(Task_Name !="ambient noise")%>%
  filter(Task_Name !="break_time_mod")%>%
  mutate(Task_Name = str_replace_all(Task_Name, " ", "_"),
         Task_Name = str_replace_all(Task_Name, "\\(", ""),
         Task_Name = str_replace_all(Task_Name, "\\)", ""),
         Task_Name = str_replace_all(Task_Name, "\\-", ""),
         Task_Name_mod = paste(Task_Name,Spreadsheet,sep="_"),
         Task_Name = str_replace_all(Task_Name, "\\&", ""),
         Task_Name = str_replace_all(Task_Name, "\\:", ""),)

#my_df_list <- node_data$Task_Name

list_o_data <- list()

#make the list of all dataframes
for (n in 1:nrow(node_data)) {
  if(node_data$n[n]==1){
    tasks_name <- node_data$Task_Name[n]
    data_nodes <- node_data %>%
      filter(Task_Name == tasks_name)%>%
      select(all_nodes)
  } else {
    tasks_name <- node_data$Task_Name_mod[n]
    data_nodes <- node_data %>%
      filter(Task_Name_mod == tasks_name)%>%
      select(all_nodes)
  }
  nodes <- str_replace(data_nodes[1, ], "_", "|")
  task_dat <- list.files(file_path, pattern = nodes, full.names = TRUE) %>%
      map_df(~read_csv(.x)%>% mutate(across(.fns = as.character)))
  list_o_data[[tasks_name]] <- task_dat
}

# Access the data frames in the list using names
length(list_o_data)
#View(list_o_data)
list_o_data

# Function to replace spaces with dots in column names
replace_spaces_with_dots <- function(df) {
  colnames(df) <- gsub(" ", ".", colnames(df))
  return(df)
}
#make the colnames better for later
list_o_data <- lapply(list_o_data, replace_spaces_with_dots)

# Create a new folder based on the project name
csv_folder_path <- file.path(master_path, "rds_folder",paste(project,"_CSVs"))
if (!dir.exists(csv_folder_path)){
  dir.create(csv_folder_path, showWarnings = FALSE)
  } else {
    print("folder already exists!")
    }

for (i in seq_along(list_o_data)) {
  df <- list_o_data[[i]]
  df_name <- names(list_o_data)[i]
  file_name <- paste(project, df_name, "csv", sep = "_")
  file_path <- file.path(csv_folder_path, file_name)
  write.csv(df, file_path, row.names = FALSE)
}

# Load the list back into R
#loaded_list <- readRDS("my_data_list.rds")
```


```{r}
#read in all ET data
file_path_ET<-file.path(file_path,"uploads")
pattern= "eyetracking_collection"
list_o_files<-list.files(file_path_ET,pattern,full.names = TRUE)
et_data <- data.frame(matrix(ncol = 1, nrow = 0))
file_path_ET
list_o_files
for (file in list_o_files) {
  lister<-read.xlsx(file)
  lister$file_name<-file
  et_data<-rbind(et_data,lister)
}
```

Seperate out ET data here
```{r}



```

#node_experiment key
```{r}
df<-data
colnames(df)<-str_replace_all(colnames(df), " " , "_")
colnames(df)<-str_replace_all(colnames(df), "-" , "_")
df<-unique(df%>%select(Experiment_ID,Experiment_Version,Task_Name,Tree_Node_Key,randomiser_4kvj,Spreadsheet))
df$Tree_Node_Key<-str_replace(df$Tree_Node_Key,"task-","")
df$Tree_Node_Key<-str_replace(df$Tree_Node_Key,"questionnaire-","")
df<-df%>%mutate(Spreadsheet=if_else(is.na(Spreadsheet),"questionnaire",Spreadsheet))
df_wider<-df%>%
  na.omit()%>%
  group_by(Task_Name,Spreadsheet)%>%
  mutate(id=cur_group_id(),id_list=row_number())%>%
  select(id,Experiment_ID,Experiment_Version,Task_Name,Spreadsheet,randomiser_4kvj,Tree_Node_Key)%>%
  pivot_wider(names_from = randomiser_4kvj,values_from = Tree_Node_Key)%>%
  select(-id)%>%
  mutate(all_nodes = paste(music_first,language_first,sep="_"))
df_wider<-apply(df_wider,2,as.character)
name<-file.path(master_path,"workflow_data",paste(project,"node_exp_spreadhseet_key.csv",sep="_"))
name
write.csv(df_wider,name)
```

#ET_data
```{r}
et_man<-et_data
et_man<-et_man%>%
  select(-"0")
et_man<-et_man%>%
  mutate(end=str_split(file_name, pattern="k-", n = Inf, simplify = T)[,2])%>%
  mutate(Tree_Node_Key=substr(end,1,4))%>%
  select(-c(end,file_name))%>%
  select(last_col(),everything())
  

name_et<-file.path(master_path,"workflow_data",paste(project,"cleaned_master_et_data.csv",sep="_"))
write.csv(et_data,name_et)
```
#singing data in folders
```{r}
#singing files
#create folders for moving files

#variables
#the main directory
mainDir<-master_path
#main_dir <- "/Users/adambramlett/scripts/music_project_23/data"
#where you will looking for the files
search_folder<-paste(file.path(mainDir,project),"/uploads",sep="")
search_folder
#new folder big branch
new_folder_name<- "singing_data"
#new folder names small branch
sub_1<-"happy_bday"
sub_2<-"professional_singing"
#the patterns to look for
pattern_of_files_1<- "Happybirthday"
pattern_of_files_2<- "originalrecording"
path_1<-paste(mainDir,"/",new_folder_name,"/",sub_1,"/",sep = "")
path_2<-paste(mainDir,"/",new_folder_name,"/",sub_2,"/",sep = "")
new_file<-file.path(mainDir,"singing")

#make files
if (!dir.exists(new_file)){
dir.create(file.path(mainDir,new_folder_name,sub_1), recursive = TRUE)
dir.create(file.path(mainDir,new_folder_name,sub_2), recursive = TRUE)
} else {
    print("folder already exists!")
}

files_to_move_1<-list.files(search_folder,pattern =pattern_of_files_1,full.names = T)
files_to_move_2<-list.files(search_folder,pattern =pattern_of_files_2,full.names = T)

file.copy(from=files_to_move_1, to=path_1)
file.copy(from=files_to_move_2, to=path_2)
```

